on: [push, pull_request]
name: Lint
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-CS-Fixer
      uses: docker://benpdavison/php-cs-fixer-php-7.3
      with:
        args: --diff --dry-run
